# Generated by Django 2.1.4 on 2019-11-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False, 'ordering': ['mode', 'product', 'year', 'id']},
        ),
    ]
